# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionHouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='buy_it_now_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='current_bid',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='current_bid_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bid_buyer', to='AuctionHouse.User'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image_description',
            field=models.ImageField(blank=True, null=True, upload_to='goods_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image_description_2',
            field=models.ImageField(blank=True, null=True, upload_to='goods_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image_description_3',
            field=models.ImageField(blank=True, null=True, upload_to='goods_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image_description_4',
            field=models.ImageField(blank=True, null=True, upload_to='goods_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image_description_5',
            field=models.ImageField(blank=True, null=True, upload_to='goods_image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('OA', '仅限拍卖'), ('OB', '拍卖与一口价'), ('PB', '仅限一口价')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='start_bid',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='user_portrait/'),
        ),
    ]
